name: Notification Maïwenn ❤️

on:
  workflow_dispatch:

jobs:
  envoyer-message:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Préparer le message du jour
        id: message
        run: |
          JOUR=1
          
          MESSAGE=$(jq -r ".[] | select(.jour == $JOUR) | .texte" messages.json)
          TITRE=$(jq -r ".[] | select(.jour == $JOUR) | .titre" messages.json)

          echo "texte=$MESSAGE" >> $GITHUB_OUTPUT
          echo "titre=$TITRE" >> $GITHUB_OUTPUT

      - name: Envoyer notification OneSignal
        env:
          ONESIGNAL_APP_ID: ${{ secrets.ONESIGNAL_APP_ID }}
          ONESIGNAL_REST_API_KEY: ${{ secrets.ONESIGNAL_REST_API_KEY }}

        run: |
          curl --request POST \
            --url https://api.onesignal.com/notifications \
            --header "Content-Type: application/json" \
            --header "Authorization: Key $ONESIGNAL_REST_API_KEY" \
            --data '{
              "app_id": "'"$ONESIGNAL_APP_ID"'",
              "include_subscription_ids": [
                "30999893-407b-41f8-a9b6-48d6a6b42507"
              ],
              "headings": {
                "en": "'"${{ steps.message.outputs.titre }}"'"
              },
              "contents": {
                "en": "'"${{ steps.message.outputs.texte }}"'"
              },
              "chrome_web_icon": "https://payent.github.io/Ma-wenn/icon.png"
            }'
